feat(sys): fallback to alacritty on old GPUs and update laptop brightness keybinds
- Add a 0.2s timeout check for ghostty to fallback to alacritty on OpenGL errors
- Replace ddcutil with brightnessctl and swayosd-client for smoother brightness handling
- Use bindel instead of binde to allow brightness adjustments while locked
- Add brightnessctl to package installation list

diff --git a/bin/myterm b/bin/myterm
--- a/bin/myterm
+++ b/bin/myterm
@@ -2,9 +2,14 @@
 
 # (First ghostty, then try alacritty if any error)
 if command -v ghostty >/dev/null 2>&1; then
-    TERM_BIN="ghostty"
+	GHOSTTY_ERR=$(timeout 0.2 ghostty -e exit 2>&1)
+	if echo "$GHOSTTY_ERR" | grep -Ei "failed|error|vulkan|opengl|gl|wgpu|panic" >/dev/null 2>&1;then
+		TERM_BIN="alacritty"
+	else
+		TERM_BIN="ghostty"
+	fi
 else
-    TERM_BIN="alacritty"
+	TERM_BIN="alacritty"
 fi
 
 # ghostty != alacritty
